### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by TimsFong** [xiaoleGun/treble_build_miku#7]
last one no sound

**Comment by xiaoleGun** [comment]
Emmm, I haven't encountered it on my phone

**Comment by xiaoleGun** [comment]
Okay, I noticed that it has been fixed

https://github.com/xiaoleGun/treble_build_miku/commit/122ce115373a64e3a54c750c6f0efce4a603fae9#diff-d22753f0fd71a47bd14d51d4b554fc7c50e2715544d728a76a66df7707e411a1

**Comment by xuejiyuki** [comment]
This problem still exists

The specific manifestation is that the button prompt tone and incoming call ringtone have disappeared, while playing the media is normal.

My phone is OPPO A9

**Comment by xiaoleGun** [comment]
https://github.com/xiaoleGun/treble_build_miku/releases/tag/TDA-0.13.3_2

Fixed
